import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local'

import React from 'react';


const helveticaFont = localFont({src: './fonts/helvetica/HelveticaNeueCyr-Medium.otf', variable: '--font-helvetica'});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${helveticaFont.className} h-svh`}>{children}</body>
    </html>
  );
}
